version: "3"
services:
    broker:
        #not used anymore; just here for debugging
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    nodered:
        build: ./node_red_image
        volumes:
            - ../flows:/flows
        ports:
            - "1880:1880"
        environment:
            - FLOWS=/flows/main_flow.json
    database:
        image: mongo:latest
        ports:
            - "27017:27017"
    server:
        build: ../dbjs
        depends_on:
            - "database"
            - "broker"
        command: >
            /bin/sh -c "
                sleep 10;
                echo starting..
                node ./httpClient/httpServer.js
            "
        ports:
            - "9090:9090"
