version: "3"
services:
    broker:
        #not used anymore; just here for debugging
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    nodered:
        build: ./node_red_image
        volumes:
            - ../flows:/flows
        ports:
            - "1880:1880"
        environment:
            - FLOWS=/flows/main_flow.json
    database:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - "8081:8081"
