version: "3"
services:
    broker:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    nodered:
        image: nodered/node-red-docker
        volumes:
            - ../flows:/flows
        ports:
            - "1880:1880"
        environment:
            - FLOWS=/flows/main_flow.json
    database:
        image: mongo:latest
        ports: 
            - "8081:8081"
